name: CI

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer Composer pour la gestion des dépendances
      - name: Install Composer
        uses: php-actions/composer@v6

      # Exécuter les tests PHPUnit
      - name: Run PHPUnit tests
        uses: php-actions/phpunit@v2
        with:
          php_version: "8.2"  # Spécifier PHP 8.2
          php_extensions: "pdo mbstring xml curl sqlite3 pdo-sqlite gd"
          # Spécifier la configuration et les autres options pour PHPUnit
          configuration: "phpunit.xml"  # Si tu as un fichier phpunit.xml personnalisé
          memory_limit: "256M"  # Limite mémoire si nécessaire
