name: CI

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer les dépendances via Composer
      - name: Install Composer dependencies
        uses: php-actions/composer@v6

      # Exécuter les tests PHPUnit avec l'action php-actions/phpunit
      - name: Run PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          # Spécifie la configuration pour PHPUnit (si nécessaire)
          configuration: "phpunit.xml"  # Ou un autre fichier de config si nécessaire
          # Si tu veux utiliser un autre fichier de tests, tu peux aussi définir un autre argument
          filter: "tst"  # Ou l'argument pour cibler ton répertoire de tests
